### ISSUE TITLE
I would like to join your team and contribute with my many years of experience and skills.

### ISSUE THREAD

**Issue by johnsmith0212** [subcoin-project/subcoin#6]
Hi, I'm Ethan Tan, a seasoned web full-stack and blockchain developer with over 8 years of experience in the industry. I specialize in building robust, scalable web applications and innovative blockchain solutions. Leveraging my expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, I deliver high-quality, secure, and efficient solutions tailored to meet your specific needs.

**Comment by liuchengxu** [comment]
Thanks for your interest. Subcoin is a Rust implementation of Bitcoin protocol, Solidity is unrelated, we may need frontend expertise in the future, but not now. You are welcome to watch our progress and see if there is anything you could help later.

**Comment by johnsmith0212** [comment]
My stack is react, typescript, node.js, solidity, rust, c++, python, php
